apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawing-index-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drawing-index-api
  template:
    metadata:
      labels:
        app: drawing-index-api
    spec:
      containers:
      - name: api
        image: drawing-index-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: REDIS_URL
          value: redis://redis-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: drawing-index-api-service
spec:
  selector:
    app: drawing-index-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
