"""Add saved searches table

Revision ID: add_saved_searches_table
Revises: ec1627021429
Create Date: 2024-08-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_saved_searches_table'
down_revision = 'ec1627021429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('drawing_type', sa.String(length=50), nullable=True),
    sa.Column('sort_by', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.String(length=10), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for performance
    op.create_index('ix_saved_searches_project_id', 'saved_searches', ['project_id'])
    op.create_index('ix_saved_searches_display_order', 'saved_searches', ['project_id', 'display_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_searches_display_order', 'saved_searches')
    op.drop_index('ix_saved_searches_project_id', 'saved_searches')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###