"""Add file_hash column for duplicate detection

Revision ID: bf9dde09109a
Revises: add_processing_tasks_simple
Create Date: 2025-07-15 18:25:46.398035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9dde09109a'
down_revision = 'add_processing_tasks_simple'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_drawings_file_hash'), 'drawings', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawings_file_hash'), table_name='drawings')
    op.drop_column('drawings', 'file_hash')
    # ### end Alembic commands ###